const prompt = require("prompt-sync")(); // Ask for user inputs
let gameCharacter = prompt("what is your name?: ");
let weapon = prompt("what is your choice of weapon?: ");
let main_enemy = prompt('what is the primary race in this world?: ')
let food = prompt("what is your favorite food?: ")
let sidecharacter = prompt('who would you like to also be in your story (just their name)?: ')
let dog = prompt('what do you want your dogs name to be?: ')
let valuable = prompt('what is your favorite piece of jeweralry?: ') 
let story = `you wake up in a cave you and you hear water running and you see a little boy in the corner when you approch him he calls out to you ${gameCharacter}!!! and then he hands you a ` + weapon + ' you must protect me from the ' + main_enemy + ' please i beg of you i just have to pay off some debt to them 100 gold coins to be exact. you recluntanlty agree to protect this little boy from ' + main_enemy + ' you begin to head out fo the cave getting blinded by the light as you when your eyes are done adjusting to the new light you look around and see ' + sidecharacter + ' you approach him as he is making '+ food + ' your eyes light up as you see it your stomach starts to grumble you ask them if you may have some as you are starving he seems reluntent to give you food but he sees your frail body and he deciedes that it is best for him to give you food you thank them for the food and you talk with '+sidecharacter + ' after chatting with them for a while you get up to continue your expedidition as you cotinue you see a dog barking at something up a tree you grab the coller thats in the tree and see his name is '+ dog + ' you look at the back of the coller to see that it has scrathched into it DO NOT RETURN so you decied to keep the dog for yourself as you contuine walking you see some '+main_enemy+ ' so you and '+dog+ ' prephare for a fight you ready your '+weapon+' as you get closer they get alertered so you fight them off killing 2 and the rest flee away as you scavenge the camp you find ' +valuable+' which you dont think much of but as you show the little boy he seems very surpried taht you are holding such a valubale the boys says that is enough to pay off my whole debt and then some so yo head to a town to pawn of your ' +valuable+' as you reach a shop he looks at it and imedaitly offers oup 1000 gold coins for ir and you agree you pay off the debts of the child and you buy a small house in the village to live with ' +dog+ ' the end'
console.log(story);